# Generated by Django 4.2.9 on 2025-01-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("version", models.CharField(max_length=50, verbose_name="版本")),
                ("enabled", models.BooleanField(default=False, verbose_name="是否启用")),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "插件",
                "verbose_name_plural": "插件",
                "ordering": ["-created_at"],
            },
        ),
    ]
