# Generated by Django 4.2.18 on 2025-02-10 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backup", "0002_alter_backup_options_alter_backupconfig_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="backup",
            table=None,
        ),
        migrations.AlterModelTable(
            name="backupconfig",
            table=None,
        ),
    ]
