# Generated by Django 4.2.18 on 2025-02-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_fix_storage_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="storage_quota",
            field=models.BigIntegerField(
                default=1073741824,
                help_text="用户存储配额(字节)",
                verbose_name="存储配额",
            ),
        ),
    ]
