# Generated by Django 4.2.18 on 2025-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="auto_save_content",
            field=models.JSONField(blank=True, help_text="自动保存的内容", null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="auto_save_excerpt",
            field=models.TextField(blank=True, null=True, verbose_name="自动保存摘要"),
        ),
        migrations.AddField(
            model_name="post",
            name="auto_save_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="自动保存时间"),
        ),
        migrations.AddField(
            model_name="post",
            name="auto_save_title",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="自动保存标题"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="version",
            field=models.IntegerField(default=1, help_text="文章版本号"),
        ),
    ]
