# Generated by Django 4.2.18 on 2025-02-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_post_auto_save_content_post_auto_save_excerpt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="allow_comment",
            field=models.BooleanField(default=True, verbose_name="允许评论"),
        ),
        migrations.AddField(
            model_name="post",
            name="pinned",
            field=models.BooleanField(default=False, verbose_name="是否置顶"),
        ),
    ]
