# Generated by Django 4.2.18 on 2025-02-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0005_fix_nullable_fields_manually"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="cover",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="封面图"
            ),
        ),
    ]
