# Generated by Django 4.2.18 on 2025-02-08 13:22

from django.db import migrations, models

import apps.core.models.statistics


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatistics",
            name="date",
            field=models.DateField(default=apps.core.models.statistics.get_today),
        ),
        migrations.AlterField(
            model_name="visitstatistics",
            name="date",
            field=models.DateField(default=apps.core.models.statistics.get_today),
        ),
    ]
