# Generated by Django 4.2.18 on 2025-02-08 14:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_userstatistics_date_alter_visitstatistics_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileStorage",
            fields=[
                (
                    "file_id",
                    models.CharField(
                        help_text="文件ID",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_name",
                    models.CharField(help_text="原始文件名", max_length=255),
                ),
                ("file_type", models.CharField(help_text="文件类型", max_length=20)),
                ("mime_type", models.CharField(help_text="MIME类型", max_length=100)),
                ("file_size", models.BigIntegerField(help_text="文件大小(字节)")),
                ("file_content", models.BinaryField(help_text="文件内容")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="更新时间"),
                ),
            ],
            options={
                "verbose_name": "文件存储",
                "verbose_name_plural": "文件存储",
                "db_table": "core_file_storage",
                "ordering": ["-created_at"],
            },
        ),
    ]
